/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HandleRouteImport } from './routes/$handle'
import { Route as AboutRouteImport } from './routes/about'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as OauthClientMetadataDotjsonRouteImport } from './routes/oauth-client-metadata[.]json'
import { Route as DotwellKnownDidDotjsonRouteImport } from './routes/[.]well-known.did[.]json'
import { Route as ApiSplatRouteImport } from './routes/api.$'
import { Route as ApiBoardsRouteImport } from './routes/api.boards'
import { Route as ApiEventsRouteImport } from './routes/api.events'
import { Route as ApiFollowsRouteImport } from './routes/api.follows'
import { Route as ApiPostsRouteImport } from './routes/api.posts'
import { Route as ApiReactionsRouteImport } from './routes/api.reactions'
import { Route as ApiRemovalsRouteImport } from './routes/api.removals'
import { Route as OauthCallbackRouteImport } from './routes/oauth.callback'
import { Route as OauthLoginRouteImport } from './routes/oauth.login'
import { Route as OauthLogoutRouteImport } from './routes/oauth.logout'
import { Route as PostPostIdRouteImport } from './routes/post.$postId'
import { Route as SyncHealthRouteImport } from './routes/sync.health'
import { Route as XrpcComDotatprotoDotsimplespaceDotcheckUserAccessRouteImport } from './routes/xrpc.com[.]atproto[.]simplespace[.]checkUserAccess'
import { Route as XrpcComDotatprotoDotspaceDotnotifySpaceDeletedRouteImport } from './routes/xrpc.com[.]atproto[.]space[.]notifySpaceDeleted'
import { Route as XrpcComDotatprotoDotspaceDotnotifyWriteRouteImport } from './routes/xrpc.com[.]atproto[.]space[.]notifyWrite'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HandleRoute = HandleRouteImport.update({
  id: '/$handle',
  path: '/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthClientMetadataDotjsonRoute =
  OauthClientMetadataDotjsonRouteImport.update({
    id: '/oauth-client-metadata.json',
    path: '/oauth-client-metadata.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotwellKnownDidDotjsonRoute = DotwellKnownDidDotjsonRouteImport.update({
  id: '/.well-known/did.json',
  path: '/.well-known/did.json',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBoardsRoute = ApiBoardsRouteImport.update({
  id: '/api/boards',
  path: '/api/boards',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEventsRoute = ApiEventsRouteImport.update({
  id: '/api/events',
  path: '/api/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFollowsRoute = ApiFollowsRouteImport.update({
  id: '/api/follows',
  path: '/api/follows',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPostsRoute = ApiPostsRouteImport.update({
  id: '/api/posts',
  path: '/api/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReactionsRoute = ApiReactionsRouteImport.update({
  id: '/api/reactions',
  path: '/api/reactions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRemovalsRoute = ApiRemovalsRouteImport.update({
  id: '/api/removals',
  path: '/api/removals',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthCallbackRoute = OauthCallbackRouteImport.update({
  id: '/oauth/callback',
  path: '/oauth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthLoginRoute = OauthLoginRouteImport.update({
  id: '/oauth/login',
  path: '/oauth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthLogoutRoute = OauthLogoutRouteImport.update({
  id: '/oauth/logout',
  path: '/oauth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const PostPostIdRoute = PostPostIdRouteImport.update({
  id: '/post/$postId',
  path: '/post/$postId',
  getParentRoute: () => rootRouteImport,
} as any)
const SyncHealthRoute = SyncHealthRouteImport.update({
  id: '/sync/health',
  path: '/sync/health',
  getParentRoute: () => rootRouteImport,
} as any)
const XrpcComDotatprotoDotsimplespaceDotcheckUserAccessRoute =
  XrpcComDotatprotoDotsimplespaceDotcheckUserAccessRouteImport.update({
    id: '/xrpc/com.atproto.simplespace.checkUserAccess',
    path: '/xrpc/com.atproto.simplespace.checkUserAccess',
    getParentRoute: () => rootRouteImport,
  } as any)
const XrpcComDotatprotoDotspaceDotnotifySpaceDeletedRoute =
  XrpcComDotatprotoDotspaceDotnotifySpaceDeletedRouteImport.update({
    id: '/xrpc/com.atproto.space.notifySpaceDeleted',
    path: '/xrpc/com.atproto.space.notifySpaceDeleted',
    getParentRoute: () => rootRouteImport,
  } as any)
const XrpcComDotatprotoDotspaceDotnotifyWriteRoute =
  XrpcComDotatprotoDotspaceDotnotifyWriteRouteImport.update({
    id: '/xrpc/com.atproto.space.notifyWrite',
    path: '/xrpc/com.atproto.space.notifyWrite',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$handle': typeof HandleRoute
  '/about': typeof AboutRoute
  '/notifications': typeof NotificationsRoute
  '/oauth-client-metadata.json': typeof OauthClientMetadataDotjsonRoute
  '/.well-known/did.json': typeof DotwellKnownDidDotjsonRoute
  '/api/$': typeof ApiSplatRoute
  '/api/boards': typeof ApiBoardsRoute
  '/api/events': typeof ApiEventsRoute
  '/api/follows': typeof ApiFollowsRoute
  '/api/posts': typeof ApiPostsRoute
  '/api/reactions': typeof ApiReactionsRoute
  '/api/removals': typeof ApiRemovalsRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/oauth/login': typeof OauthLoginRoute
  '/oauth/logout': typeof OauthLogoutRoute
  '/post/$postId': typeof PostPostIdRoute
  '/sync/health': typeof SyncHealthRoute
  '/xrpc/com.atproto.simplespace.checkUserAccess': typeof XrpcComDotatprotoDotsimplespaceDotcheckUserAccessRoute
  '/xrpc/com.atproto.space.notifySpaceDeleted': typeof XrpcComDotatprotoDotspaceDotnotifySpaceDeletedRoute
  '/xrpc/com.atproto.space.notifyWrite': typeof XrpcComDotatprotoDotspaceDotnotifyWriteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$handle': typeof HandleRoute
  '/about': typeof AboutRoute
  '/notifications': typeof NotificationsRoute
  '/oauth-client-metadata.json': typeof OauthClientMetadataDotjsonRoute
  '/.well-known/did.json': typeof DotwellKnownDidDotjsonRoute
  '/api/$': typeof ApiSplatRoute
  '/api/boards': typeof ApiBoardsRoute
  '/api/events': typeof ApiEventsRoute
  '/api/follows': typeof ApiFollowsRoute
  '/api/posts': typeof ApiPostsRoute
  '/api/reactions': typeof ApiReactionsRoute
  '/api/removals': typeof ApiRemovalsRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/oauth/login': typeof OauthLoginRoute
  '/oauth/logout': typeof OauthLogoutRoute
  '/post/$postId': typeof PostPostIdRoute
  '/sync/health': typeof SyncHealthRoute
  '/xrpc/com.atproto.simplespace.checkUserAccess': typeof XrpcComDotatprotoDotsimplespaceDotcheckUserAccessRoute
  '/xrpc/com.atproto.space.notifySpaceDeleted': typeof XrpcComDotatprotoDotspaceDotnotifySpaceDeletedRoute
  '/xrpc/com.atproto.space.notifyWrite': typeof XrpcComDotatprotoDotspaceDotnotifyWriteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$handle': typeof HandleRoute
  '/about': typeof AboutRoute
  '/notifications': typeof NotificationsRoute
  '/oauth-client-metadata.json': typeof OauthClientMetadataDotjsonRoute
  '/.well-known/did.json': typeof DotwellKnownDidDotjsonRoute
  '/api/$': typeof ApiSplatRoute
  '/api/boards': typeof ApiBoardsRoute
  '/api/events': typeof ApiEventsRoute
  '/api/follows': typeof ApiFollowsRoute
  '/api/posts': typeof ApiPostsRoute
  '/api/reactions': typeof ApiReactionsRoute
  '/api/removals': typeof ApiRemovalsRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/oauth/login': typeof OauthLoginRoute
  '/oauth/logout': typeof OauthLogoutRoute
  '/post/$postId': typeof PostPostIdRoute
  '/sync/health': typeof SyncHealthRoute
  '/xrpc/com.atproto.simplespace.checkUserAccess': typeof XrpcComDotatprotoDotsimplespaceDotcheckUserAccessRoute
  '/xrpc/com.atproto.space.notifySpaceDeleted': typeof XrpcComDotatprotoDotspaceDotnotifySpaceDeletedRoute
  '/xrpc/com.atproto.space.notifyWrite': typeof XrpcComDotatprotoDotspaceDotnotifyWriteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$handle'
    | '/about'
    | '/notifications'
    | '/oauth-client-metadata.json'
    | '/.well-known/did.json'
    | '/api/$'
    | '/api/boards'
    | '/api/events'
    | '/api/follows'
    | '/api/posts'
    | '/api/reactions'
    | '/api/removals'
    | '/oauth/callback'
    | '/oauth/login'
    | '/oauth/logout'
    | '/post/$postId'
    | '/sync/health'
    | '/xrpc/com.atproto.simplespace.checkUserAccess'
    | '/xrpc/com.atproto.space.notifySpaceDeleted'
    | '/xrpc/com.atproto.space.notifyWrite'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$handle'
    | '/about'
    | '/notifications'
    | '/oauth-client-metadata.json'
    | '/.well-known/did.json'
    | '/api/$'
    | '/api/boards'
    | '/api/events'
    | '/api/follows'
    | '/api/posts'
    | '/api/reactions'
    | '/api/removals'
    | '/oauth/callback'
    | '/oauth/login'
    | '/oauth/logout'
    | '/post/$postId'
    | '/sync/health'
    | '/xrpc/com.atproto.simplespace.checkUserAccess'
    | '/xrpc/com.atproto.space.notifySpaceDeleted'
    | '/xrpc/com.atproto.space.notifyWrite'
  id:
    | '__root__'
    | '/'
    | '/$handle'
    | '/about'
    | '/notifications'
    | '/oauth-client-metadata.json'
    | '/.well-known/did.json'
    | '/api/$'
    | '/api/boards'
    | '/api/events'
    | '/api/follows'
    | '/api/posts'
    | '/api/reactions'
    | '/api/removals'
    | '/oauth/callback'
    | '/oauth/login'
    | '/oauth/logout'
    | '/post/$postId'
    | '/sync/health'
    | '/xrpc/com.atproto.simplespace.checkUserAccess'
    | '/xrpc/com.atproto.space.notifySpaceDeleted'
    | '/xrpc/com.atproto.space.notifyWrite'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HandleRoute: typeof HandleRoute
  AboutRoute: typeof AboutRoute
  NotificationsRoute: typeof NotificationsRoute
  OauthClientMetadataDotjsonRoute: typeof OauthClientMetadataDotjsonRoute
  DotwellKnownDidDotjsonRoute: typeof DotwellKnownDidDotjsonRoute
  ApiSplatRoute: typeof ApiSplatRoute
  ApiBoardsRoute: typeof ApiBoardsRoute
  ApiEventsRoute: typeof ApiEventsRoute
  ApiFollowsRoute: typeof ApiFollowsRoute
  ApiPostsRoute: typeof ApiPostsRoute
  ApiReactionsRoute: typeof ApiReactionsRoute
  ApiRemovalsRoute: typeof ApiRemovalsRoute
  OauthCallbackRoute: typeof OauthCallbackRoute
  OauthLoginRoute: typeof OauthLoginRoute
  OauthLogoutRoute: typeof OauthLogoutRoute
  PostPostIdRoute: typeof PostPostIdRoute
  SyncHealthRoute: typeof SyncHealthRoute
  XrpcComDotatprotoDotsimplespaceDotcheckUserAccessRoute: typeof XrpcComDotatprotoDotsimplespaceDotcheckUserAccessRoute
  XrpcComDotatprotoDotspaceDotnotifySpaceDeletedRoute: typeof XrpcComDotatprotoDotspaceDotnotifySpaceDeletedRoute
  XrpcComDotatprotoDotspaceDotnotifyWriteRoute: typeof XrpcComDotatprotoDotspaceDotnotifyWriteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$handle': {
      id: '/$handle'
      path: '/$handle'
      fullPath: '/$handle'
      preLoaderRoute: typeof HandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth-client-metadata.json': {
      id: '/oauth-client-metadata.json'
      path: '/oauth-client-metadata.json'
      fullPath: '/oauth-client-metadata.json'
      preLoaderRoute: typeof OauthClientMetadataDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/did.json': {
      id: '/.well-known/did.json'
      path: '/.well-known/did.json'
      fullPath: '/.well-known/did.json'
      preLoaderRoute: typeof DotwellKnownDidDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/boards': {
      id: '/api/boards'
      path: '/api/boards'
      fullPath: '/api/boards'
      preLoaderRoute: typeof ApiBoardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/events': {
      id: '/api/events'
      path: '/api/events'
      fullPath: '/api/events'
      preLoaderRoute: typeof ApiEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/follows': {
      id: '/api/follows'
      path: '/api/follows'
      fullPath: '/api/follows'
      preLoaderRoute: typeof ApiFollowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/posts': {
      id: '/api/posts'
      path: '/api/posts'
      fullPath: '/api/posts'
      preLoaderRoute: typeof ApiPostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reactions': {
      id: '/api/reactions'
      path: '/api/reactions'
      fullPath: '/api/reactions'
      preLoaderRoute: typeof ApiReactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/removals': {
      id: '/api/removals'
      path: '/api/removals'
      fullPath: '/api/removals'
      preLoaderRoute: typeof ApiRemovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/callback': {
      id: '/oauth/callback'
      path: '/oauth/callback'
      fullPath: '/oauth/callback'
      preLoaderRoute: typeof OauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/login': {
      id: '/oauth/login'
      path: '/oauth/login'
      fullPath: '/oauth/login'
      preLoaderRoute: typeof OauthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/logout': {
      id: '/oauth/logout'
      path: '/oauth/logout'
      fullPath: '/oauth/logout'
      preLoaderRoute: typeof OauthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post/$postId': {
      id: '/post/$postId'
      path: '/post/$postId'
      fullPath: '/post/$postId'
      preLoaderRoute: typeof PostPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sync/health': {
      id: '/sync/health'
      path: '/sync/health'
      fullPath: '/sync/health'
      preLoaderRoute: typeof SyncHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/xrpc/com.atproto.simplespace.checkUserAccess': {
      id: '/xrpc/com.atproto.simplespace.checkUserAccess'
      path: '/xrpc/com.atproto.simplespace.checkUserAccess'
      fullPath: '/xrpc/com.atproto.simplespace.checkUserAccess'
      preLoaderRoute: typeof XrpcComDotatprotoDotsimplespaceDotcheckUserAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/xrpc/com.atproto.space.notifySpaceDeleted': {
      id: '/xrpc/com.atproto.space.notifySpaceDeleted'
      path: '/xrpc/com.atproto.space.notifySpaceDeleted'
      fullPath: '/xrpc/com.atproto.space.notifySpaceDeleted'
      preLoaderRoute: typeof XrpcComDotatprotoDotspaceDotnotifySpaceDeletedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/xrpc/com.atproto.space.notifyWrite': {
      id: '/xrpc/com.atproto.space.notifyWrite'
      path: '/xrpc/com.atproto.space.notifyWrite'
      fullPath: '/xrpc/com.atproto.space.notifyWrite'
      preLoaderRoute: typeof XrpcComDotatprotoDotspaceDotnotifyWriteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HandleRoute: HandleRoute,
  AboutRoute: AboutRoute,
  NotificationsRoute: NotificationsRoute,
  OauthClientMetadataDotjsonRoute: OauthClientMetadataDotjsonRoute,
  DotwellKnownDidDotjsonRoute: DotwellKnownDidDotjsonRoute,
  ApiSplatRoute: ApiSplatRoute,
  ApiBoardsRoute: ApiBoardsRoute,
  ApiEventsRoute: ApiEventsRoute,
  ApiFollowsRoute: ApiFollowsRoute,
  ApiPostsRoute: ApiPostsRoute,
  ApiReactionsRoute: ApiReactionsRoute,
  ApiRemovalsRoute: ApiRemovalsRoute,
  OauthCallbackRoute: OauthCallbackRoute,
  OauthLoginRoute: OauthLoginRoute,
  OauthLogoutRoute: OauthLogoutRoute,
  PostPostIdRoute: PostPostIdRoute,
  SyncHealthRoute: SyncHealthRoute,
  XrpcComDotatprotoDotsimplespaceDotcheckUserAccessRoute:
    XrpcComDotatprotoDotsimplespaceDotcheckUserAccessRoute,
  XrpcComDotatprotoDotspaceDotnotifySpaceDeletedRoute:
    XrpcComDotatprotoDotspaceDotnotifySpaceDeletedRoute,
  XrpcComDotatprotoDotspaceDotnotifyWriteRoute:
    XrpcComDotatprotoDotspaceDotnotifyWriteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
